---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.3.2
serverless_language: ''
refresh_interval_floor:
polling_url: 'https://data.lpp.si/api/station/timetable?station-code={{ station_code }}{% assign lines = bus_lines | split: "," %}{% for line in lines %}&route-group-number={{ line | strip }}{% endfor %}&next-hours={{ next_hours }}&previous-hours={{ previous_hours }}'
polling_headers: ''
polling_body: ''
id: 482855
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  description: Displays a station's timetable for LPP buses in Ljubljana, Slovenia.
  github_url: https://github.com/dsoklic/TRMNL-LPP-timetable
  category: custom,travel
- keyname: station_code
  field_type: string
  name: Station Code
  description: The LPP station code. Get it <a href="https://www.lpp.si/sites/default/files/lpp_vozniredi/iskalnik/index.php" class="underline">here</a>.
  placeholder: '600011'
- keyname: bus_lines
  field_type: multi_string
  name: Bus Lines
  description: Line numbers to show, one per line (e.g. 6 and 8).
  placeholder: '6'
- keyname: next_hours
  field_type: number
  name: Next Hours
  optional: true
  default: 3
  min: 0
  description: How far into the future to show departures.
- keyname: previous_hours
  field_type: number
  name: Previous Hours
  optional: true
  default: 0
  min: 0
  description: How far into the past to show departures.
name: LPP Ljubljana Timetable
description: LPP Ljubljana departure timetable
refresh_interval: 15
